# Generated by Django 2.1.5 on 2022-04-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.IntegerField(default='')),
                ('val2', models.IntegerField(default='')),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
