# Generated by Django 2.1.5 on 2021-12-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('password', models.CharField(max_length=19)),
                ('cpassword', models.CharField(default='', max_length=19)),
            ],
        ),
    ]
